{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.denko",
    "module": "logging-starter",
    "version": "1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.1-SNAPSHOT.jar",
          "url": "logging-starter-1.1-SNAPSHOT.jar",
          "size": 1105,
          "sha512": "02d810b77c1170af4d2813d342978f27ddf3f5c210cc025cf107449bec826a20962b213e1d63dfac80a697d1fa2edb8a2cd1a752a3dca668705edb5ce07541c3",
          "sha256": "5a5861defaf84fb7183c01e086213838338758df4cf9089079af75cba5920a39",
          "sha1": "e892601a66e1b0cdfb59de73de0c5dacff444809",
          "md5": "5ff54cad3a7b1bcc4d84c606a740be9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-starter-1.1-SNAPSHOT.jar",
          "url": "logging-starter-1.1-SNAPSHOT.jar",
          "size": 1105,
          "sha512": "02d810b77c1170af4d2813d342978f27ddf3f5c210cc025cf107449bec826a20962b213e1d63dfac80a697d1fa2edb8a2cd1a752a3dca668705edb5ce07541c3",
          "sha256": "5a5861defaf84fb7183c01e086213838338758df4cf9089079af75cba5920a39",
          "sha1": "e892601a66e1b0cdfb59de73de0c5dacff444809",
          "md5": "5ff54cad3a7b1bcc4d84c606a740be9c"
        }
      ]
    }
  ]
}
