{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.denko",
    "module": "logging-starter",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.0-SNAPSHOT.jar",
          "url": "logging-starter-1.0-SNAPSHOT.jar",
          "size": 1105,
          "sha512": "83316f5744151b0e8f2a473e9382a8317429db084f3e6f46096263e14bf7cdedd897867ef1fa6ab83ac59b972db3c4a1dbb92a217e277156499a848b025a3a93",
          "sha256": "67b53a12873559c582ab19fb46c3ebe56f82649337b31bde86545710c956e81e",
          "sha1": "295a5bdbf94532e29b3e6745605d2629ce3772b7",
          "md5": "3f20acf07fb93e85f6fb8729c38ade66"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-starter-1.0-SNAPSHOT.jar",
          "url": "logging-starter-1.0-SNAPSHOT.jar",
          "size": 1105,
          "sha512": "83316f5744151b0e8f2a473e9382a8317429db084f3e6f46096263e14bf7cdedd897867ef1fa6ab83ac59b972db3c4a1dbb92a217e277156499a848b025a3a93",
          "sha256": "67b53a12873559c582ab19fb46c3ebe56f82649337b31bde86545710c956e81e",
          "sha1": "295a5bdbf94532e29b3e6745605d2629ce3772b7",
          "md5": "3f20acf07fb93e85f6fb8729c38ade66"
        }
      ]
    }
  ]
}
